// não aceita repetição e não é indexada. (não tem índices para os elementos)

const times = new Set()
times.add('Vasco')
times.add('Sao Paulo').add('Palmeiras').add('Corinthians')
times.add('Flamengo')
times.add('Vasco')
//adicionou Vasco uma única vez (é case sensitive. Letra maiuscula e minúscula importa.)
console.log('times')
console.log(times)
console.log('times.size')
console.log(times.size)
console.log('times.has("Vasco")')
console.log(times.has("Vasco"))
console.log('times.has("vasco")')
console.log(times.has("vasco"))
times.delete('Flamengo')
console.log('depois do comando times.delete("Flamengo")')
console.log('time.has("Flamengo")')
console.log(times.has("Flamengo"))

const nomes = ['Raquel', 'Lucas', 'Julia', 'Lucas']
const nomesSet = new Set(nomes)
console.log('\nnomes')
console.log(nomes)
console.log('nomesSet')
console.log(nomesSet)
